# Generated by Django 2.2.5 on 2019-11-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100, verbose_name='작성자')),
                ('affiliation', models.CharField(max_length=200, verbose_name='소속')),
                ('position', models.CharField(max_length=100, verbose_name='직책')),
                ('fields', models.CharField(help_text='주요분야 선택, 두개 이상 선택 가능', max_length=50)),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('ev1', models.IntegerField(choices=[(5, '아주 높음'), (4, '높음'), (3, '보통'), (2, '약함'), (1, '취약')], help_text='5가지 선택지 중 하나를 선택해 주세요.', verbose_name='전문성')),
                ('ev2', models.IntegerField(choices=[(5, '아주 높음'), (4, '높음'), (3, '보통'), (2, '약함'), (1, '취약')], help_text='5가지 선택지 중 하나를 선택해 주세요.', verbose_name='성실성')),
                ('etc', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
